version: '3.5'

services:
  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: .
      dockerfile: ./.deployment/docker/containers/php/Dockerfile
    depends_on:
      - database
    env_file:
      - .env
    networks:
      service:
        aliases:
          - pod
    environment:
      - ENV=/home/www-data/.ashrc
    volumes:
      - ./:/srv/app/:rw
      - ./.deployment/docker/containers/php/www.conf:/etc/php8.1.3/php-fpm.conf
      - ./.deployment/docker/containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./.deployment/docker/aliases/.ashrc:/home/www-data/.ashrc
    command: --define opcache.validate_timestamps=On

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    depends_on:
      - php
    image: nginx:1.20-alpine
    environment:
      - HTTPS_METHOD=noredirect
    networks:
      - service
    volumes:
      - ./public:/srv/app/public:ro
      - ./.deployment/docker/containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8080"

  database:
    container_name: ${PROJECT_NAME}_database
    image: mariadb:10.4.19
    env_file:
      - .env
    networks:
      - service
    volumes:
      - database_docker:/var/lib/mysql
    ports:
      - "8001:3306"

  rabbitmq:
    restart: unless-stopped
    container_name: ${PROJECT_NAME}_rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    networks:
      - service
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    ports:
      - "8002:5672"
      - "8003:15672"

  maildev:
    restart: unless-stopped
    container_name: ${PROJECT_NAME}_maildev
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    networks:
      - service
    ports:
      - "8004:80"
      - "8005:25"

volumes:
  rabbitmq_volume: {}
  database_docker: {}

networks:
  service:
    name: service
